### ISSUE TITLE
Enable all features for docs.rs

### ISSUE THREAD

**Issue by museun** [museun/alto_logger#1]
This should be added to cargo.toml before the next release
```toml
[package.metadata.docs.rs]
features = ["time"] 
```
